/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RestaurantsIndexRouteImport } from './routes/restaurants.index'
import { Route as RestaurantsRestaurantIdRouteImport } from './routes/restaurants.$restaurantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIndexRoute = RestaurantsIndexRouteImport.update({
  id: '/restaurants/',
  path: '/restaurants/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRestaurantIdRoute = RestaurantsRestaurantIdRouteImport.update({
  id: '/restaurants/$restaurantId',
  path: '/restaurants/$restaurantId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/kitchen': typeof KitchenRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/restaurants/$restaurantId': typeof RestaurantsRestaurantIdRoute
  '/restaurants/': typeof RestaurantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/kitchen': typeof KitchenRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/restaurants/$restaurantId': typeof RestaurantsRestaurantIdRoute
  '/restaurants': typeof RestaurantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/kitchen': typeof KitchenRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/restaurants/$restaurantId': typeof RestaurantsRestaurantIdRoute
  '/restaurants/': typeof RestaurantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/categories'
    | '/dashboard'
    | '/kitchen'
    | '/orders'
    | '/products'
    | '/restaurants/$restaurantId'
    | '/restaurants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/categories'
    | '/dashboard'
    | '/kitchen'
    | '/orders'
    | '/products'
    | '/restaurants/$restaurantId'
    | '/restaurants'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/categories'
    | '/dashboard'
    | '/kitchen'
    | '/orders'
    | '/products'
    | '/restaurants/$restaurantId'
    | '/restaurants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CategoriesRoute: typeof CategoriesRoute
  DashboardRoute: typeof DashboardRoute
  KitchenRoute: typeof KitchenRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  RestaurantsRestaurantIdRoute: typeof RestaurantsRestaurantIdRoute
  RestaurantsIndexRoute: typeof RestaurantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/': {
      id: '/restaurants/'
      path: '/restaurants'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof RestaurantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$restaurantId': {
      id: '/restaurants/$restaurantId'
      path: '/restaurants/$restaurantId'
      fullPath: '/restaurants/$restaurantId'
      preLoaderRoute: typeof RestaurantsRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CategoriesRoute: CategoriesRoute,
  DashboardRoute: DashboardRoute,
  KitchenRoute: KitchenRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  RestaurantsRestaurantIdRoute: RestaurantsRestaurantIdRoute,
  RestaurantsIndexRoute: RestaurantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
